SUPABASE_URL = "https://aroaxeqoofkhamsowrhc.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFyb2F4ZXFvb2ZraGFtc293cmhjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2MTUwNzEsImV4cCI6MjA3MzE5MTA3MX0.EwMkE5MikK7VWLwAHMNoQ1a-uzWzdVKhV9XvW0R06Qo"
SUPABASE_SERVICE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFyb2F4ZXFvb2ZraGFtc293cmhjIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1NzYxNTA3MSwiZXhwIjoyMDczMTkxMDcxfQ.t5IXHGY_Qh-NJdeYOGAhJoBjter_n8JDwZW_b7Ys3yI"
Supabase_password = "YgvtyawVG0vzx1Hz"

[users]
admin = { password = "4dm1n_2025!" }
yurani_ballesteros = { password = "v1at1c0s_2025!" }

