# Example Streamlit Secrets Configuration
#
# IMPORTANT: This is an EXAMPLE file. Do NOT use these credentials in production!
#
# To use this:
# 1. Copy this file to .streamlit/secrets.toml
# 2. Replace the passwords with actual secure passwords
# 3. Never commit secrets.toml to Git
# 4. Add .streamlit/secrets.toml to .gitignore

[users]
# Admin user - Full access to all features
admin = { password = "admin123" }

# Regular users
usuario1 = { password = "password123" }
usuario2 = { password = "mypassword" }

# Example: Uncomment and modify to add more users
# jorge = { password = "jorge2025" }
# maria = { password = "maria2025" }
# carlos = { password = "carlos2025" }
# ana = { password = "ana2025" }

# For production, use strong passwords:
# - At least 12 characters
# - Mix of uppercase, lowercase, numbers, and symbols
# - Example: "P@ssw0rd!2025#Secure"
